spring.application.name: TaskManager

spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: pass
  jpa.database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true